export const CATEGORIES = [
  "Concerts",
  "Sports",
  "Theater",
  "Festivals",
  "Comedy",
  "Family",
  "Arts",
  "Other"
];

export const LOCATIONS = [
  "New York",
  "Los Angeles",
  "Chicago",
  "Miami",
  "Dallas",
  "San Francisco",
  "Seattle",
  "Denver",
  "Boston",
  "Austin"
];

export const SAMPLE_EVENTS = [
  {
    uuid: "taylor-swift-eras-tour",
    id: "1",
    title: "Taylor Swift | The Eras Tour",
    description: "Experience Taylor Swift's record-breaking Eras Tour, showcasing music from all phases of her iconic career. The show features elaborate sets, multiple costume changes, and all her biggest hits across a spectacular 3-hour performance.",
    shortDescription: "Taylor Swift's record-breaking tour featuring music from all eras of her career",
    date: "2025-06-15",
    time: "19:00",
    location: "New York",
    venue: "Madison Square Garden",
    category: "Concerts",
    image: "https://images.pexels.com/photos/1190297/pexels-photo-1190297.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    price: 199.99,
    currency: "USD",
    availability: 0,
    isHighDemand: true,
    waitingRoomOpens: "2025-06-01T09:30:00Z",
    salesStart: "2025-06-01T10:00:00Z"
  },
  {
    uuid: "nba-finals-2025",
    id: "2",
    title: "NBA Finals 2025",
    description: "Witness basketball history at the NBA Finals 2025. Experience the culmination of the season as the two best teams in the league battle for the championship in this best-of-seven series finale.",
    shortDescription: "The championship final of the National Basketball Association",
    date: "2025-06-20",
    time: "20:00",
    location: "Los Angeles",
    venue: "Crypto.com Arena",
    category: "Sports",
    image: "https://images.pexels.com/photos/1752757/pexels-photo-1752757.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    price: 350,
    currency: "USD",
    availability: 120,
    isHighDemand: true,
    waitingRoomOpens: "2025-05-25T13:30:00Z",
    salesStart: "2025-05-25T14:00:00Z"
  },
  {
    uuid: "hamilton-the-musical",
    id: "3",
    title: "Hamilton: The Musical",
    description: "Don't miss the chance to see the revolutionary musical that took Broadway by storm. Hamilton tells the story of America's founding father Alexander Hamilton through a blend of hip-hop, jazz, R&B, and traditional show tunes.",
    shortDescription: "Award-winning musical about the life of American founding father Alexander Hamilton",
    date: "2025-07-05",
    time: "19:30",
    location: "Chicago",
    venue: "CIBC Theatre",
    category: "Theater",
    image: "https://images.pexels.com/photos/11323792/pexels-photo-11323792.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    price: 179.50,
    currency: "USD",
    availability: 50,
    isHighDemand: true,
    waitingRoomOpens: "2025-06-15T09:30:00Z",
    salesStart: "2025-06-15T10:00:00Z"
  },
  {
    uuid: "coachella-2025",
    id: "4",
    title: "Coachella Music Festival 2025",
    description: "Join the world's most famous music and arts festival featuring the biggest artists across all genres, stunning art installations, and an unforgettable experience in the California desert.",
    shortDescription: "World-famous annual music and arts festival in the California desert",
    date: "2025-04-10",
    time: "12:00",
    location: "Indio",
    venue: "Empire Polo Club",
    category: "Festivals",
    image: "https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    price: 499,
    currency: "USD",
    availability: 200,
    isHighDemand: true,
    waitingRoomOpens: "2025-01-10T09:30:00Z",
    salesStart: "2025-01-10T10:00:00Z"
  },
  {
    uuid: "kevin-hart-reality-check",
    id: "5",
    title: "Kevin Hart: Reality Check Tour",
    description: "Laugh until it hurts with Kevin Hart's latest world tour. Experience one of comedy's biggest stars as he delivers his signature high-energy performance and hilarious observations on life, family, and success.",
    shortDescription: "Kevin Hart's latest world comedy tour with all-new material",
    date: "2025-05-25",
    time: "20:00",
    location: "Miami",
    venue: "FTX Arena",
    category: "Comedy",
    image: "https://images.pexels.com/photos/713149/pexels-photo-713149.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    price: 89.99,
    currency: "USD",
    availability: 300,
    isHighDemand: false
  },
  {
    uuid: "disney-on-ice-magic-of-dreams",
    id: "6",
    title: "Disney On Ice: Magic of Dreams",
    description: "Disney On Ice presents Magic of Dreams, where beloved Disney characters take to the ice in a spectacular skating showcase. Featuring characters from Frozen, Moana, Toy Story, and more, this show promises fun for the whole family.",
    shortDescription: "Family-friendly ice skating show featuring beloved Disney characters",
    date: "2025-03-15",
    time: "14:00",
    location: "Dallas",
    venue: "American Airlines Center",
    category: "Family",
    image: "https://images.pexels.com/photos/2570807/pexels-photo-2570807.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    price: 59.99,
    currency: "USD",
    availability: 450,
    isHighDemand: false
  }
];